### ISSUE TITLE
Fehler in den Funktionnamen

### ISSUE THREAD

**Issue by OpossumCrash** [vicrudakov/WA_Gruppenarbeit#7]
@vicrudakov, bei dir enthalten die Namen von Funktionen den Punkt zwischen Wörter. So werden üblicherweise solche Funktionen in R benannt, die zu eine Funktionsklasse gehören und für bestimmte Datenstruktur allgemeine Funktion spezialisieren. Mir scheint, dass ist nicht, was du gemeint hast. Versuche die Punkte durch _ ersetzen.

**Comment by OpossumCrash** [comment]
Das betrifft auch die Variablennamen

**Comment by vicrudakov** [comment]
Habe alles geändert, Danke!

**Comment by Gruenhaarige** [comment]
Ich habe solchen Fehler bei mir gefunden und auch mit _ statt mit . geschrieben
